# Generated by Django 5.2.3 on 2025-06-15 06:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legalgen', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advocate',
            name='address',
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.TextField(blank=True, null=True)),
                ('document', models.FileField(blank=True, null=True, upload_to='client_documents/')),
                ('Date', models.DateTimeField(auto_now_add=True)),
                ('filer', models.CharField(blank=True, max_length=100, null=True)),
                ('advocate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clients', to='legalgen.advocate')),
            ],
        ),
    ]
