# Generated by Django 5.2.3 on 2025-06-15 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legalgen', '0002_remove_advocate_address_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='advocate',
            name='Address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
