# Generated by Django 5.2.3 on 2025-06-15 09:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legalgen', '0004_remove_client_address_remove_client_advocate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='advocate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clients', to='legalgen.advocate'),
        ),
    ]
