# Generated by Django 5.2.3 on 2025-06-15 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('legalgen', '0005_client_advocate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='advocate',
            old_name='Address',
            new_name='address',
        ),
    ]
