# Generated by Django 5.2.3 on 2025-06-15 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legalgen', '0006_rename_address_advocate_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='documents/'),
        ),
    ]
