# Generated by Django 5.2.3 on 2025-06-15 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legalgen', '0007_client_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='reason',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
