# Generated by Django 5.2.3 on 2025-06-15 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legalgen', '0008_client_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='Date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
