# Generated by Django 5.2.3 on 2025-06-16 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legalgen', '0009_alter_client_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='document',
            new_name='document_version_1',
        ),
        migrations.AddField(
            model_name='client',
            name='document_version_2',
            field=models.FileField(blank=True, null=True, upload_to='documents/'),
        ),
    ]
