# Generated by Django 5.2.3 on 2025-06-17 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legalgen', '0010_rename_document_client_document_version_1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NDA_Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disclosing_party_name', models.CharField(max_length=255)),
                ('disclosing_party_representative', models.CharField(max_length=255)),
                ('disclosing_party_title', models.CharField(max_length=255)),
                ('disclosing_party_address', models.TextField()),
                ('receiving_party_name', models.CharField(max_length=255)),
                ('receiving_party_representative', models.CharField(max_length=255)),
                ('receiving_party_title', models.CharField(max_length=255)),
                ('receiving_party_address', models.TextField()),
                ('effective_date', models.DateField()),
                ('duration', models.PositiveSmallIntegerField(help_text='Duration in years')),
                ('definition_confidential_information', models.TextField()),
                ('non_competition', models.BooleanField(default=False)),
                ('non_competition_duration', models.PositiveSmallIntegerField(blank=True, help_text='Non-competition duration in years', null=True)),
                ('non_circumvention', models.BooleanField(default=False)),
                ('intellectual_property_rights', models.TextField(blank=True, null=True)),
                ('data_destruction_policy', models.TextField(blank=True, null=True)),
                ('penalties', models.TextField(blank=True, null=True)),
                ('jurisdiction', models.TextField(blank=True, null=True)),
                ('dispute_resolution_method', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
