# Generated by Django 5.2.3 on 2025-06-18 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legalgen', '0011_nda_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nda_details',
            name='definition_confidential_information',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='nda_details',
            name='disclosing_party_address',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='nda_details',
            name='disclosing_party_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='nda_details',
            name='disclosing_party_representative',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='nda_details',
            name='disclosing_party_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='nda_details',
            name='effective_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='nda_details',
            name='receiving_party_address',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='nda_details',
            name='receiving_party_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='nda_details',
            name='receiving_party_representative',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='nda_details',
            name='receiving_party_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
