# Generated by Django 5.2.3 on 2025-06-18 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('legalgen', '0012_alter_nda_details_definition_confidential_information_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nda_details',
            name='created_at',
        ),
    ]
