# Generated by Django 5.2.3 on 2025-06-18 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legalgen', '0013_remove_nda_details_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='marriage_Date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
