# Generated by Django 5.2.3 on 2025-06-18 09:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legalgen', '0014_alter_client_marriage_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='nda_details',
            name='advocate',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nda_details', to='legalgen.advocate'),
        ),
        migrations.AddField(
            model_name='nda_details',
            name='client_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='nda_details',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nda_details',
            name='document_version_1',
            field=models.FileField(blank=True, null=True, upload_to='nda_docs/'),
        ),
        migrations.AddField(
            model_name='nda_details',
            name='document_version_2',
            field=models.FileField(blank=True, null=True, upload_to='nda_docs/'),
        ),
    ]
