# Generated by Django 5.2.3 on 2025-06-18 12:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legalgen', '0015_nda_details_advocate_nda_details_client_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NoObjectionCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(blank=True, max_length=255, null=True)),
                ('noc_type', models.CharField(blank=True, choices=[('Property Transfer', 'Property Transfer'), ('Employment', 'Employment'), ('Passport', 'Passport'), ('Vehicle Sale', 'Vehicle Sale'), ('General', 'General')], max_length=100, null=True)),
                ('party_issuing', models.CharField(blank=True, max_length=255, null=True)),
                ('party_receiving', models.CharField(blank=True, max_length=255, null=True)),
                ('purpose', models.TextField(blank=True, null=True)),
                ('date_issued', models.DateField(blank=True, null=True)),
                ('valid_until', models.DateField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('document_version_1', models.FileField(blank=True, null=True, upload_to='noc_docs/')),
                ('document_version_2', models.FileField(blank=True, null=True, upload_to='noc_docs/')),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('advocate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nocs', to='legalgen.advocate')),
            ],
        ),
        migrations.CreateModel(
            name='SaleDeed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(blank=True, max_length=255, null=True)),
                ('seller_name', models.CharField(blank=True, max_length=255, null=True)),
                ('seller_address', models.TextField(blank=True, null=True)),
                ('buyer_name', models.CharField(blank=True, max_length=255, null=True)),
                ('buyer_address', models.TextField(blank=True, null=True)),
                ('property_address', models.TextField(blank=True, null=True)),
                ('property_type', models.CharField(blank=True, choices=[('Residential', 'Residential'), ('Commercial', 'Commercial')], max_length=100, null=True)),
                ('property_description', models.TextField(blank=True, null=True)),
                ('sale_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('payment_mode', models.CharField(blank=True, choices=[('Cheque', 'Cheque'), ('Bank Transfer', 'Bank Transfer'), ('Cash', 'Cash')], max_length=100, null=True)),
                ('date_of_agreement', models.DateField(blank=True, null=True)),
                ('date_of_registration', models.DateField(blank=True, null=True)),
                ('witness_1', models.CharField(blank=True, max_length=255, null=True)),
                ('witness_2', models.CharField(blank=True, max_length=255, null=True)),
                ('document_version_1', models.FileField(blank=True, null=True, upload_to='sale_deed_docs/')),
                ('document_version_2', models.FileField(blank=True, null=True, upload_to='sale_deed_docs/')),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('advocate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sale_deeds', to='legalgen.advocate')),
            ],
        ),
    ]
