# Generated by Django 5.2.3 on 2025-06-19 12:34

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legalgen', '0016_noobjectioncertificate_saledeed'),
    ]

    operations = [
        migrations.CreateModel(
            name='LegalSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('filename', models.CharField(max_length=255)),
                ('original_text', models.TextField()),
                ('questions', models.JSONField(default=list)),
                ('answers', models.JSONField(default=dict)),
                ('filled_text', models.TextField(blank=True, null=True)),
                ('generated_pdf_path', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.FileField(blank=True, null=True, upload_to='draft_gener/')),
                ('advocate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='draft', to='legalgen.advocate')),
            ],
        ),
    ]
