# Generated by Django 5.2.3 on 2025-06-20 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legalgen', '0017_legalsession'),
    ]

    operations = [
        migrations.AddField(
            model_name='legalsession',
            name='current_question',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='legalsession',
            name='status',
            field=models.CharField(default='in_progress', max_length=50),
        ),
    ]
