# Generated by Django 5.2.3 on 2025-06-21 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legalgen', '0018_legalsession_current_question_legalsession_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='advocate',
            name='degree',
            field=models.CharField(help_text='Example: BA LL.B., BBA LL.B., B.Com LL.B.', max_length=100, null=True),
        ),
    ]
