# Generated by Django 5.2.3 on 2025-06-21 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('legalgen', '0019_advocate_degree'),
    ]

    operations = [
        migrations.RenameField(
            model_name='advocate',
            old_name='degree',
            new_name='education',
        ),
    ]
